### ISSUE TITLE
Expose "append_decorations" as a dedicated functionality, separately from load

### ISSUE THREAD

**Issue by Firefly35** [boostorg/dll#21]
In some cases, I'd expect to be able to compute the complete full path of the shared library as an boost::filesystem::path prior to load the library.
I'd like to have a method (maybe static ?) such as 
`boost::filesystem::path shared_library::append_decorations(const boost::filesystem::path & path)` exposed in shared_library class.

**Comment by apolukhin** [comment]
I'm afraid this is not possible. `append_decorations` tries to guess the name, so it may try to open multiple different names, stopping at first success.

If you have some consistent naming of your libraries/plugins then you can use the suffix function https://github.com/boostorg/dll/blob/8c641504e9a7ee6ccb16dfa77ed1fc089f4a9675/include/boost/dll/shared_library.hpp#L510 to get the right extension and form a library name.
