### ISSUE TITLE
Bad error message due to fall off

### ISSUE THREAD

**Issue by Firefly35** [boostorg/dll#22]
Hello,
using boost::dll in my XPCF dynamic component framework (boost::dll is used in https://github.com/b-com-software-basis repository xpcf in the ModuleManager.cpp file), a module (i.e. a shared library) developer has met the following issue :
- The instantiated component C inherits a I interface, in the component implementation, the declaration of a pure virtual method of I (declared as override in the component header) was not in the component:: scope
- Dynamically loading the module failed and the output message from boost::dll is "boost::dll::shared_library::load() failed (dlerror system message: .../shared/debug/module: cannot open shared object file: No such file or directory): Bad file descriptor"

The issue appeared on linux (on Mac, clang complains for missing symbols at the module link time, hence prevent the issue to append).

Investigating inside shared_library_impl.hpp, it appears that errors (in this case dlerror = missing symbol) with load_mode = append_decorations are not handled in the scope. 
Leaving the append_decoration scope in error, there is a try to open the file with the specified path (which is incomplete as it misses the lib prefix and the .so suffix), that results in the erroneous error message "bad file descriptor".

I'd expect boost::dll to check if the current error is a bad _file_descriptor, in such a case to try opening the exactly specified path. Otherwise, other errors should be returned immediately before the append_decorations scope ends.

Or maybe, if append_decorations fails, boost should return the error without trying to open the exact specified path : it is the user responsibility to provide an abstract shared library name when used in conjunction with append_decorations ?

Environment: 
g++ version is 7.3.0, boost 1.68 built with c++14 option on ubuntu 18.04.

Best regards

**Comment by apolukhin** [comment]
This one should be fixed in develop branch by #23 
Closing
