### ISSUE TITLE
BOOST_DLL_ALIAS does not export symbol on MinGW-w64

### ISSUE THREAD

**Issue by markand** [boostorg/dll#24]
On MinGW-w64, the BOOST_DLL_ALIAS does not export symbol. I presume this is because the macro  only declares avariable and GCC strips it.

```cpp
#define BOOST_DLL_ALIAS_SECTIONED(FunctionOrVar, AliasName, SectionName)                        \
    namespace _autoaliases {                                                                    \
        extern "C" BOOST_SYMBOL_EXPORT const void *AliasName;                                   \
    } /* namespace _autoaliases */                                                              \
    /**/
```

If I try to do manually the same in a source file. It confirms my thoughts:

**Using a defined function**

```cpp
extern "C" {

__declspec(dllexport)
int my_super_mario_function()
{
    return 0;
}

}
```

Once built, the symbol appears correctly:

```
$ g++ -std=c++17 -shared -o plugin.dll plugin.cpp -fvisibility=hidden -lboost_system-mt && nm plugin.dll | grep my_
0000000067e8142d t _GLOBAL__sub_I__ZN6custom11my_functionEv
0000000067e813b0 T _ZN6custom11my_functionEv
0000000067e813cb T my_super_mario_function
```

**Using a simple declaration**

```cpp
extern "C" {

__declspec(dllexport)
int my_super_mario_function();

}
```

In that case, no symbol is exported.

```
$ g++ -std=c++17 -shared -o plugin.dll plugin.cpp -fvisibility=hidden -lboost_system-mt && nm plugin.dll | grep my_
0000000067e81422 t _GLOBAL__sub_I__ZN6custom11my_functionEv
0000000067e813b0 T _ZN6custom11my_functionEv
```

However, assigning a value seems to work, but a bit ugly.

```cpp
namespace custom {

void my_function()
{
        puts("CALLED");
}

} // !custom

extern "C" {

__declspec(dllexport) void* my_super_function = reinterpret_cast<void*>(&(custom::my_function));

}
```

The symbol is there:

```
$ g++ -std=c++17 -shared -o plugin.dll plugin.cpp -fvisibility=hidden -lboost_system-mt && nm plugin.dll | grep my_
0000000067e81422 t _GLOBAL__sub_I__ZN6custom11my_functionEv
0000000067e813b0 T _ZN6custom11my_functionEv
0000000067e85010 D my_super_function
```

What can we do to fix that issue? Is there a compile flag that export declared symbol?

**Comment by markand** [comment]
Okay, just realized there was the [Limitations](https://www.boost.org/doc/libs/1_68_0/doc/html/boost_dll/limitations.html) par that explains this.

Note to myself: always read the whole documentation before asking.
Proposal: make this limitation section part of "Getting started" chapter.

**Comment by apolukhin** [comment]
That won't help :(
The topic is quite complex, the FAQ and Misuses chapters may be also very important to start using the library.

**Comment by markand** [comment]
By the way, why make this option and not the behaviour under BOOST_DLL_FORCE_ALIAS_INSTANTIATION define the default? That would solve this problem easily. Also, I do think that a library should *work* immediately without any user option to be set. That is, the option BOOST_DLL_FORCE_ALIAS_INSTANTIATION should be the opposite. What do you think?

**Comment by apolukhin** [comment]
Did not fully get the idea, but sounds like a breaking change
