### ISSUE TITLE
Any interest to replace boost functionalities with std ones ?

### ISSUE THREAD

**Issue by Firefly35** [boostorg/dll#27]
Hi Antony,
do you think there is some value to replace some of boost::dll boost dependencies with std:: ones when available ?
Typically, I think about shared_ptr, type_traits, move, asserts and so on..

**Comment by apolukhin** [comment]
Yes, but without breaking the C++03 builds. And with a macro to change the dependencies back to the Boost ones.

**Comment by apolukhin** [comment]
Come back with a PR if there's still interest in such functionality
