### ISSUE TITLE
DeImangle does not match when smart_library calls import_Imangled with const T* or std ::string

### ISSUE THREAD

**Issue by XiaLiChao82** [boostorg/dll#32]
DeImangle does not match when smart_library calls import_Imangled with const T* or std ::string.I solved this problem by modifying the type_rule function of itanium.h file. The modified code is as follows:
    
template<typename T>
    std::string type_rule(const std::string & type_name)
    {
        using namespace std;

//-        return  type_name +
// -               const_rule<T>() +
// -               volatile_rule<T>() +
// -               reference_rule<T>();
    +    (void)type_name;
    +   return boost::core::demangle(typeid (T).name()) + const_rule<T>() + volatile_rule<T>() + reference_rule<T>();
    }

**Comment by RamilGauss** [comment]
I met this bug too.
For example (for Linux only):
class MyClass{
template <typename T>
int Func(){return 42;}
};
import_mangled<MyClass, int( void )>( lib, "Func<float>" ); // throw exception!!!

Because: in Linux export table contains "int MyClass::Func<float>()", but expected in import_mangled "MyClass::Func<float>()".

**Comment by apolukhin** [comment]
I'm out of time for the next X months, so this issue would not be solved soon. But if you provide a Pull Request with test case and a fix, then I'll be happy to merge it.

**Comment by RamilGauss** [comment]
Ok.

**Comment by XiaLiChao82** [comment]
The problem I encountered was that the CV qualifier string order of the pointer type in mangled exported under Linux was inconsistent with demangled, causing an exception to be thrown, such as const char* (ctti::type_index: const char*; demangled: char const*), same for template type.

**Comment by RamilGauss** [comment]
Hello, XiaLiChao82. 
Can you give an example of code in which there will definitely be an exception?

**Comment by XiaLiChao82** [comment]
> Hello, XiaLiChao82.
> Can you give an example of code in which there will definitely be an exception?
[linux]
#test.h
namespace space {

class my_plugin_api {
 public:
  virtual const char* name() const = 0;

  virtual ~my_plugin_api() {}
};

class BOOST_SYMBOL_EXPORT my_plugin : public my_plugin_api {
  QByteArray _name;
  std::function<void(const char*, const char*, const char*)> callback;

 public:
  const char* name() const;
  float calculate(float x, float y);
  int calculate(const int x, const int y);
  void set_name(char* name);
  void set_name(const std::string& name);
  void set_callback(
      const std::function<void(const char*, const char*, const char*)>&,
      const char*,
      const char*,
      const char*);
  static std::size_t size();
  my_plugin();
  my_plugin(const char*);
  ~my_plugin();
  static int value;
};
}

#test.cpp
#include "test.h"
const char* space::my_plugin::name() const {
  return _name;
}
float space::my_plugin::calculate(float x, float y) {
  return x / y;
}
int space::my_plugin::calculate(const int x, const int y) {
  return x / y;
}
void space::my_plugin::set_name(char* name) {
  _name = name;
}
void space::my_plugin::set_name(const std::string& name) {
  _name = name.c_str();
}
void space::my_plugin::set_callback(
    const std::function<void(const char*, const char*, const char*)>& _cb,
    const char* c1,
    const char* c2,
    const char* c3) {
  callback = _cb;
  callback(c1, c2, c3);
}
std::size_t space::my_plugin::size() {
  return sizeof(my_plugin);
}
space::my_plugin::my_plugin(const char* name) : _name(name) {}
space::my_plugin::my_plugin() : _name("Empty") {}
space::my_plugin::~my_plugin() {}
int space::my_plugin::value = 42;

#main.cpp
#include <boost/dll/import_class.hpp>
#include <boost/dll/import_mangled.hpp>
#include <boost/dll/smart_library.hpp>  // for import_alias
#include <boost/filesystem.hpp>
#include <boost/signals2.hpp>
#include <boost/type_index.hpp>
#include <boost/type_index/ctti_type_index.hpp>
#include <boost/type_index/stl_type_index.hpp>
#include <chrono>
#include <iostream>
#include <memory>
#include <string>
#include <typeinfo>

int main(int argc, char *argv[]) {
auto cl =
      import_class<class Alias, const char *>(lib, plugin_name, size, "_name");
//demangled: space::my_plugin(char const*)
//real results: space::my_plugin(const char*)
  cout << "imported class" << endl;

  auto callback = cl.call<void(
      const std::function<void(const char *, const char *, const char *)> &,
      const char *, const char *, const char *)>("set_callback");

//demangled: space::my_plugin::set_callback(std::function<void (char const*, char const*, char const*)>&)
//real results: space::my_plugin::set_callback(std::function<void(const char*, const char*, const char*)>&)
  callback(&printStr, "A", "B", "C");

  auto name = import_mangled<const Alias, const char *()>(lib, "name");
  std::cout << "Name: " << (cl->*name)() << std::endl;
  //    (cl->*name)();
  // import both calculate functions
  auto calc =
      import_mangled<Alias, float(float, float), int(const int, const int)>(
          lib, "calculate");
  std::cout << "Calc(float): " << (cl->*calc)(5.f, 2.f) << std::endl;
  std::cout << "Calc(int): " << (cl->*calc)(5, 2) << std::endl;
  auto setname = import_mangled<Alias, void(const std::string &)>(lib, "set_name");
  char newName[] = "newName";
  std::string stringNewName = "stringName";
  (cl->*setname)(stringNewName);
  std::cout << "new Name: " << (cl->*name)() << std::endl;
  cout << "name:" << (t->*get_name)() << endl;
  return 0;
}

**Comment by apolukhin** [comment]
Fixed in #35
