### ISSUE TITLE
Compilation error 'getline': identifier not found

### ISSUE THREAD

**Issue by slay-er** [boostorg/dll#43]
Hi,

on Windows I get the following compilation error.

include\boost\dll\detail\pe_info.hpp(291,13): error C3861: 'getline': identifier not found
include\boost\dll\detail\pe_info.hpp(291,13): error C3861:             getline(fs, symbol_name, '\0');
include\boost\dll\detail\pe_info.hpp(291,13): error C3861:             ^

When I change the include of **cstring** to **string** it works.

According to cppreference std::getline is defined in header _string_.
https://en.cppreference.com/w/cpp/string/basic_string/getline

**Comment by apolukhin** [comment]
Many thanks for the report!
