### ISSUE TITLE
Unable to compile with clang 9 with enabled modules

### ISSUE THREAD

**Issue by faserg1** [boostorg/dll#45]
So the trouble is here:
```
.../vcpkg_installed/x64-linux/include/boost/dll/import.hpp:132:30: error: expected unqualified-id
BOOST_DLL_IMPORT_RESULT_TYPE import(const boost::dll::fs::path& lib, const char* name,
                             ^
.../vcpkg_installed/x64-linux/include/boost/dll/import.hpp:146:18: fatal error: 'T' file not found
    return import<T>(lib, name.c_str(), mode);
```

**Comment by apolukhin** [comment]
This is going to be a breaking change, but there's no choice. Renamed `import` into `import symbol`.

Many thanks for the report!

**Comment by vinipsmaker** [comment]
> This is going to be a breaking change, but there's no choice.

It's understandable.

Anyway it'd be nice to at least mention this breaking change at: https://www.boost.org/doc/libs/1_76_0/doc/html/boost_dll/revision_history.html

I've had to go through the commit history to understand what happened.
