### ISSUE TITLE
On Linux, Boost dll requires linking against dl, why not do this in the CMakeLists.txt?

### ISSUE THREAD

**Issue by joris-nijs** [boostorg/dll#67]
The boost dll documentation documentation suggests to link against dl on Linux: [https://www.boost.org/doc/libs/1_84_0/doc/html/boost_dll/getting_started.html](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_dll/getting_started.html).

Would there be reason not to do this already in the Boost dll CMakeLists.txt when using the CMake integration?

**Comment by apolukhin** [comment]
Many thanks for the report! Fixed
