### ISSUE TITLE
Buffer size 10240 for FreeBSD in program_location_impl.hpp

### ISSUE THREAD

**Issue by darealshinji** [boostorg/dll#70]
In `boost/dll/detail/posix/program_location_impl.hpp` for FreeBSD the buffer size is 10240. Is that correct or a typo and it should be 1024?

https://github.com/boostorg/dll/blob/6c60dde50bf67138c90cc84938111866813feaff/include/boost/dll/detail/posix/program_location_impl.hpp#L71

**Comment by apolukhin** [comment]
Thanks for the report, changed the function logic!
